////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

*The* recommended mechanism for generating and maintaining your Cyclades installations as it enables a configurable and reproducible 
(operationally maintainable) artifact from the specifics of this workspace.

== Basic Features

This is a deployment and configuration control mechanism for a Cyclades installation. This mechanism is highly recommended
for generating and maintaining your Cyclades installations as it enables a configurable and reproducible (operationally maintainable) artifact
from the specifics of this workspace. Downloading and building this template workspace will generate a Cyclades installation with all of the
current Cyclades SOA Nyxlets included by default. Use this as a template to create tailored Cyclades deployments for variable requirements
...i.e. different environments, different service pools etc...

* Provides a reproducible mechanism for generating deployments
    ** Nyxlets/Services 
        *** Nyxlet selection
        *** Versions
        *** Configurations
    ** Cyclades Service Engine 
        *** Core and shared library selection
        *** Core and shared library versions
        *** Configurations
    ** J2EE configurations (i.e. database pools, JNDI configurations etc...)
* Provided template builds and packages the default Cyclades complete installation (war file generated)
* Simply duplicate and modify this provided template for custom deployments

== Overview

This document describes the steps involved for deploying a complete Cyclades default installation using the Cyclades SOA deployment build and packaging mechanism. Please follow the instructions below.

== Generate And Deploy The Complete Cyclades SOA Default Distribution

. Install Gradle (if you do not already have it): http://www.gradle.org

. Install Tomcat (if you do not already have it): http://tomcat.apache.org (We're running on Tomcat 7) This could be a standard installation on any host, local or remote

. Download and install (extract) a stable version of this repository to a directory of choice (example: "/cycladessoa")
	.. https://github.com/cycladessoa/cyclades-deployment/archive/master.zip (We'll assume the extracted directory is "/cycladessoa/cyclades-deployment" for our purposes)

. From within the directory "/cycladessoa/cyclades-deployment" run the command _gradle clean build_

. The Cyclades Service Engine binary distribution exists within a Nyxlet's workspace _build/libs_ directory after a successful build (_build/libs/cyclades.war_). Simply copy this file to your Tomcat installation's "webapps" directory and be sure to preserve the name "cyclades.war".

. Restart Tomcat and verify the installation
	.. http://localhost:8080/cyclades (Core Cyclades Service Engine status page should be displayed without error)
	.. http://localhost:8080/cyclades?action=help (Help page displays without error)

== Naming

=== Terms

* *STROMA*: (protocol) Service TRansaction Orchestration Messaging Architecture
* *X-STROMA*: (protocol) "Trans", or "across" STROMA
* *Nyxlet*: A service module that is pluggable into the Cyclades Service Engine

=== Etymons

* *"Stroma"*: _Wikipedia_ (animal tissue), the connective, functionally supportive framework of a biological cell, tissue, or organ
* *"Nyx"*: _Wikipedia_ (Νύξ, "night") – Nox in Latin translation – is the Greek goddess (or personification) of the night. A shadowy figure, Nyx stood at or near the beginning of creation, and was the mother of other personified gods such as Hypnos (Sleep) and Thánatos (Death)


